# R programming recap

## The arithmetic mean computed from grouped data
As stated the _coding method_ should always be used.

__EXAMPLE__

Using Table [2.1](../../02%20Chapter%202%20Frequency%20Distributions/01%20Text/03%20Frequency%20Distributions.ipynb#Table-2-1).

In [1]:
load('../../Saves/Table_2.1.Rdata')
X <- c(61, 64, 67, 70, 73)
Table.2.1.mark <- matrix(c(X, Table.2.1), nrow=nrow(Table.2.1))
rownames(Table.2.1.mark)<-rownames(Table.2.1)
colnames(Table.2.1.mark)<-c('X', 'f')
Table.2.1.mark

      X  f
60-62 61  5
63-65 64 18
66-68 67 42
69-71 70 27
72-74 73  8

### The coding method

In [2]:
c <- 3 # class interval size
t.length <- length(Table.2.1.mark[,1])
A.idx <- 3 # guessed mean index
A <- Table.2.1.mark[A.idx,1]
u <- seq(1, t.length, by=1)-A.idx
f <- Table.2.1.mark[,2] # frequency
N <- sum(f) # summation of frequencies
fu <- f*u
fu.sum <- sum(fu)
(X.bar <- A + (fu.sum/N)*c)

[1] 67.45

In [3]:
grouped.mean <- function(X, f) {
    if(var(diff(X)) == 0) { # coding method
        idx <- ceiling(length(X)/2)
        A <- X[idx]
        N <- sum(f)
        u <- seq(1, length(X), by=1)-idx
        fu.sum <- sum(f*u)
        return(as.numeric(A+(fu.sum/N)*c))
    } else { # Long method
        fx.sum <- sum(f*X)
        N <- sum(f)
        return(as.numeric(fx.sum/N))
    }
}

In [4]:
grouped.mean(Table.2.1.mark[,1], Table.2.1.mark[,2])

[1] 67.45

### The long method

In [5]:
load('../../Saves/Table_2.10d.Rdata')
X <- c( 255.00, 265.00, 275.00, 285.00, 295.00, 310.00, 350.00)
Table.2.10.d.mark <- matrix(c(X, Table.2.10.d[,1]), nrow=nrow(Table.2.10.d))
rownames(Table.2.10.d.mark) <- rownames(Table.2.10.d)
colnames(Table.2.10.d.mark) <- c('X', 'f')
Table.2.10.d.mark

                X   f
$250.00-$259.99 255  8
260.00-269.99   265 10
270.00-279.99   275 16
280.00-289.99   285 15
290.00-299.99   295 10
300.00-319.99   310  8
320.00-379.99   350  3

In [6]:
grouped.mean(Table.2.10.d.mark[,1], Table.2.10.d.mark[,2])

[1] 283.5