# R programming recap

## Summary Statistics
R includes a variety of functions for calculating summary statistics.

In [11]:
X <- c(1, 2, 3, 4, 5)
mean(X)
median(X)
min(X)
max(X)

[1] 3

[1] 3

[1] 1

[1] 5

Each of the above functions has an argument `na.rm` for dealing with `NA` values. The default behavior is to return `NA` if any values are `NA`. If `na.r=TRUE`, then `NA` values are ignored.

In [9]:
X <- c(1, 2, 3, 4, 5, NA)
mean(X)
mean(X, na.rm=TRUE)

[1] NA

[1] 3

Outliers can be trimed from the dataset as well using the `trim` argument.

In [10]:
mean(c(-1, 0:100, 2000))
mean(c(-1, 0:100, 2000), trim=0.1)

[1] 68.43689

[1] 50

The most convenient function for looking at summary information is `summary`. It is a generic function that works on data frames, matrices, tables, factors, and other objects. As an example, let's take a look at the output of summary for an example set.

In [17]:
X <- c(
    88, 45, 53, 86, 33, 86, 85, 30, 89, 53, 41, 96, 56, 38, 62,
    71, 51, 86, 68, 29, 28, 47, 33, 37, 25, 36, 33, 94, 73, 46,
    42, 34, 79, 72, 88, 99, 82, 62, 57, 42, 28, 55, 67, 62, 60,
    96, 61, 57, 75, 93, 34, 75, 53, 32, 28, 73, 51, 69, 91, 35
)
summary(X)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  25.00   37.75   57.00   59.17   76.00   99.00

The sort function can sort out the data. and the stem function will display the distribution of the numeric vector.

In [22]:
sort(X)
stem(X)

 [1] 25 28 28 28 29 30 32 33 33 33 34 34 35 36 37 38 41 42 42 45 46 47 51 51 53
[26] 53 53 55 56 57 57 60 61 62 62 62 67 68 69 71 72 73 73 75 75 79 82 85 86 86
[51] 86 88 88 89 91 93 94 96 96 99

  The decimal point is 1 digit(s) to the right of the |

  2 | 58889
  3 | 02333445678
  4 | 122567
  5 | 113335677
  6 | 01222789
  7 | 1233559
  8 | 25666889
  9 | 134669

Another way of generating Table [2.5](../02%20Chapter%202%20Frequency%20Distributions/02%20Solved%20Problems/01%20Arrays.ipynb#Table-2-5).

In [25]:
load('../../Saves/Problem_2.2.Rdata')
stem(P2.2.data)

  The decimal point is 1 digit(s) to the right of the |

  5 | 3
  5 | 79
  6 | 00011222233
  6 | 5556778889
  7 | 111223333444
  7 | 555555566667788888999
  8 | 012234
  8 | 555678889
  9 | 0334
  9 | 5567

## The mode in R
There is no mode method in R. A reasonable version is shown below.

In [12]:
mode <- function(x) {
  unique_x <- unique(x)
  tabulate_x <- tabulate(match(x, unique_x))
  ret_val <- unique_x[tabulate_x == max(tabulate_x)]
  if(length(ret_val) == length(x)){
      return(NA)
  } else {
      return(ret_val)
  }
}

In [6]:
X <- c(2, 2, 5, 7, 9, 9, 9, 10, 10, 11, 12, 18)
mode(X)

[1] 9

In [7]:
X <- c(3, 5, 8, 10, 12, 15, 16)
mode(X)

[1] NA

In [8]:
X <- c(2, 3, 4, 4, 4, 5, 5, 7, 7, 7, 9)
mode(X)

[1] 4 7

## The arithmetic mean computed from grouped data
As stated the _coding method_ should always be used.

__EXAMPLE__

Using Table [2.1](../../02%20Chapter%202%20Frequency%20Distributions/01%20Text/03%20Frequency%20Distributions.ipynb#Table-2-1).

In [1]:
load('../../Saves/Table_2.1.Rdata')
X <- c(61, 64, 67, 70, 73)
Table.2.1.mark <- matrix(c(X, Table.2.1), nrow=nrow(Table.2.1))
rownames(Table.2.1.mark)<-rownames(Table.2.1)
colnames(Table.2.1.mark)<-c('X', 'f')
Table.2.1.mark

      X  f
60-62 61  5
63-65 64 18
66-68 67 42
69-71 70 27
72-74 73  8

### The coding method

In [2]:
c <- 3 # class interval size
t.length <- length(Table.2.1.mark[,1])
A.idx <- 3 # guessed mean index
A <- Table.2.1.mark[A.idx,1]
u <- seq(1, t.length, by=1)-A.idx
f <- Table.2.1.mark[,2] # frequency
N <- sum(f) # summation of frequencies
fu <- f*u
fu.sum <- sum(fu)
(X.bar <- A + (fu.sum/N)*c)

[1] 67.45

In [3]:
grouped.mean <- function(X, f) {
    if(var(diff(X)) == 0) { # coding method
        idx <- ceiling(length(X)/2)
        A <- X[idx]
        N <- sum(f)
        u <- seq(1, length(X), by=1)-idx
        fu.sum <- sum(f*u)
        return(as.numeric(A+(fu.sum/N)*c))
    } else { # Long method
        fx.sum <- sum(f*X)
        N <- sum(f)
        return(as.numeric(fx.sum/N))
    }
}

In [4]:
grouped.mean(Table.2.1.mark[,1], Table.2.1.mark[,2])

[1] 67.45

### The long method

In [5]:
load('../../Saves/Table_2.10d.Rdata')
X <- c( 255.00, 265.00, 275.00, 285.00, 295.00, 310.00, 350.00)
Table.2.10.d.mark <- matrix(c(X, Table.2.10.d[,1]), nrow=nrow(Table.2.10.d))
rownames(Table.2.10.d.mark) <- rownames(Table.2.10.d)
colnames(Table.2.10.d.mark) <- c('X', 'f')
Table.2.10.d.mark

                X   f
$250.00-$259.99 255  8
260.00-269.99   265 10
270.00-279.99   275 16
280.00-289.99   285 15
290.00-299.99   295 10
300.00-319.99   310  8
320.00-379.99   350  3

In [6]:
grouped.mean(Table.2.10.d.mark[,1], Table.2.10.d.mark[,2])

[1] 283.5

## Geometric mean in R

In [31]:
geometric.mean <- function(x) {
    return(exp(mean(log(x))))
}

In [34]:
X <- 2^(1:301)
geometric.mean(X)

[1] 2.854495e+45

The geometric mean shown above does not work with really large number sets.

In [36]:
geometric.mean <- function(x) {
    return(prod(x)^(1/length(x)))
}
X <- 2^(1:301)
geometric.mean(X)

[1] Inf

## Harmonic mean in R

In [1]:
harmonic.mean <- function(x) {
    return(length(x)/sum(x^(-1)))
}

In [2]:
X <- c(2, 4, 8)
round(harmonic.mean(X), 2)

[1] 3.43

## Root mean square in R

In [2]:
rms <- function(x) {
    return(sqrt(mean(x^2)))
}

In [4]:
X <- c(1, 3, 4, 5, 7)
round(rms(X), 2)

[1] 4.47

## Qunatiles in R

In [3]:
quantile(ex.17, probs=c(0.25, 0.5, 0.75, 0.9, 0.95))

  25%   50%   75%   90%   95%
37.75 57.00 76.00 89.20 94.10