# Frequency distributions
When summarizing large masses of raw data, it is often useful to distribute the data into _classes_, or _categories_, and to determine the number of individuals belonging to each class, called the _class frequency_. A tabular arrangement of data by classes together with the corresponding class frequencies is called a _frequency distribution_, or _frequency table_. [Table 2.1](#Table_2_1) is a freqency distribution of heights (recorded to the nearest inch) of $100$ male students at XYZ University.  
The first class (or category), for example, consists of heights from $60$ to $62$ in and is indicated by the range symbol `60-62`. Since five students have heights belonging to this class, the corresponding class frequency is $5$.  
Data organized and summarizzed as in the above frequency distribution are often called _grouped data_. Although the grouping process generally destroys much of the original detail of the data, an important advantage is gained in the clear "overall" picture that is obtained and in the vital relationships that are thereby made evident.

<a id="Table-2-1"></a>
<h5 style="text-align: center;">Table 2.1 Heights of 100 male students at XYZ University</h5>


| Height (in) | Number of Students |
|:-----------:|:------------------:|
|    60-62    |          5         |
|    63-65    |         18         |
|    66-68    |         42         |
|    69-71    |         27         |
|    72-74    |          8         |
|       Total |         100        |

---

Table 2.1 can be found:

In [1]:
load('../../Saves/Table_2.1.Rdata')
Table.2.1

  Height Freq
1 60-62   5
2 63-65  18
3 66-68  42
4 69-71  27
5 72-74   8

## Frequency distribution tables in R
R programming has the `table` function for generating a frequency table. Using the data in Problem [2.2](../02%20Solved%20Problems/01%20Arrays.ipynb#Problem-2-2), we have:

In [26]:
load('../../Saves/Problem_2.2.Rdata')
cat('Raw Data:', P2.2.data, '\n')
cat('Distribution Range:', stat.range <- diff(range(P2.2.data))+1, '\n')
cat('Lower boundary:', (lb <- min(P2.2.data)-.5), '\nUpper boundary:', (ub <- max(P2.2.data+.5)), '\n')
cat('Bins:', (bins <- seq(lb, ub, by=stat.range/9)), '\n\n\n')
grouped.data <- cut(P2.2.data, bins)
(P2.2.table <- table(grouped.data))
transform(P2.2.table)

Raw Data: 68 84 75 82 68 90 62 88 76 93 73 79 88 73 60 93 71 59 85 75 61 65 75 87 74 62 95 78 63 72 66 78 82 75 94 77 69 74 68 60 96 78 89 61 75 95 60 79 83 71 79 62 67 97 78 85 76 65 71 75 65 80 73 57 88 78 62 76 53 74 86 67 73 81 72 63 76 75 85 77
Distribution Range: 45
Lower boundary: 52.5
Upper boundary: 97.5
Bins: 52.5 57.5 62.5 67.5 72.5 77.5 82.5 87.5 92.5 97.5

grouped.data
(52.5,57.5] (57.5,62.5] (62.5,67.5] (67.5,72.5] (72.5,77.5] (77.5,82.5]
          2          10           8           9          20          12
(82.5,87.5] (87.5,92.5] (92.5,97.5]
          7           5           7

  grouped.data Freq
1 (52.5,57.5]   2
2 (57.5,62.5]  10
3 (62.5,67.5]   8
4 (67.5,72.5]   9
5 (72.5,77.5]  20
6 (77.5,82.5]  12
7 (82.5,87.5]   7
8 (87.5,92.5]   5
9 (92.5,97.5]   7