# Computation of moments from grouped data

## Problem 5-6
Find the first four moments about the mean for the heigh distribution of Problem [3.22](#Solution-5-6).

In [1]:
load('../../Saves//Table_3.3.Rdata')
Table.3.3

  X  u  f  fu
1 61 -2  5 -10
2 64 -1 18 -18
3 67  0 42   0
4 70  1 27  27
5 73  2  8  16

### Solution 5-6
The work can be arranged as in Table [5.2](#Table-5-2), from which we have

\begin{align}
m^\prime_1 &= c\frac{\sum{fu}}{N}=(3)\left(\frac{15}{100}\right) = 0.45 &
m^\prime_3 &= c^3\frac{\sum{fu^3}}{N} = (3)^3\left(\frac{33}{100}\right) = 8.91 \\
m^\prime_2 &= c^2\frac{\sum{fu^2}}{N} = (3)^2\left(\frac{97}{100}\right) = 8.73 &
m^\prime_4 &= c^4\frac{\sum{fu^4}}{N} = (3)^4\left(\frac{253}{100}\right) = 204.93
\end{align}

Thus

\begin{align}
m_1 &= 0 \\
m_2 &= m^\prime_2 - m^{\prime2}_1 = 8.73 - (0.45)^2 = 8.5275 \\
m_3 &= m^\prime_3 - 3m^\prime_1m^\prime_2 + m^{\prime3}_1 = 8.91 - 3(0.45)(8.73) + 2(0,45)^3 = 02.6932 \\
m_4 &= m^\prime_4 - 4m^\prime_1m^\prime_3 + 6m^{\prime2}_1m^\prime_2 - 3m^{\prime4}_1 \\
    &= 204.93 - 4(0.45)(8.91) + 6(0.45)^2(8.73) - 3(0.45)^4 = 199.3759
\end{align}

In [2]:
p5.6 <- new.env()
p5.6$N <- sum(Table.3.3$f)
p5.6$C <- (diff(Table.3.3$X)[1])
p5.6$fu2 <- Table.3.3$f*Table.3.3$u^2
p5.6$fu3 <- Table.3.3$f*Table.3.3$u^3
p5.6$fu4 <- Table.3.3$f*Table.3.3$u^4
p5.6$m1.prime <- p5.6$C*sum(Table.3.3$fu)/p5.6$N
p5.6$m2.prime <- p5.6$C^2*sum(p5.6$fu2)/p5.6$N
p5.6$m3.prime <- p5.6$C^3*sum(p5.6$fu3)/p5.6$N
p5.6$m4.prime <- p5.6$C^4*sum(p5.6$fu4)/p5.6$N
p5.6$m1 <- 0
p5.6$m2 <- p5.6$m2.prime - p5.6$m1.prime^2
p5.6$m3 <- p5.6$m3.prime - 3*p5.6$m1.prime*p5.6$m2.prime + 2*p5.6$m1.prime^3
p5.6$m4 <- p5.6$m4.prime - 4*p5.6$m1.prime*p5.6$m3.prime + 6*p5.6$m1.prime^2*p5.6$m2.prime - 3*p5.6$m1.prime^4
Table.5.2 <- Table.3.3
Table.5.2$fu2 <- p5.6$fu2; Table.5.2$fu3 <- p5.6$fu3; Table.5.2$fu4 <- p5.6$fu4
cat("m1 = ", p5.6$m1, "\nm2 = ", p5.6$m2, "\nm3 = ", p5.6$m3, "\nm4 = ", p5.6$m4)

m1 =  0
m2 =  8.5275
m3 =  -2.69325
m4 =  199.3759

#### Table-5-2

In [3]:
Table.5.2

  X  u  f  fu  fu2 fu3 fu4
1 61 -2  5 -10 20  -40  80
2 64 -1 18 -18 18  -18  18
3 67  0 42   0  0    0   0
4 70  1 27  27 27   27  27
5 73  2  8  16 32   64 128

---

## Problem 5-7
Find (a) $m^\prime_1$, (b) $m^\prime_2$, (c) $m^\prime_3$, (d) $m^\prime_4$, (e) $m_1$, (f) $m_2$, (g) $m_3$, (h) $m_4$, (i) $\bar{X}$, (j) $s$, (k) $\overline{X^2}$, and (l) $\overline{X^3}$ for the distribution in Table [4.7](#Solution-5-7) of Problem [4.19](#Solution-5-7).

### Solution 5-7
The work can be arranged as in Table [5.3](#Table-5-3).

In [4]:
p5.7 <- new.env()
p5.7$Marks <- c(70, 74, 78, 82, 86, 90, 94, 98, 102, 106, 110, 114, 118, 122, 126)
p5.7$Freq <- c(4, 9, 16, 28, 45, 66, 85, 72, 54, 38, 27, 18, 11, 5, 2)
p5.7$N <- sum(p5.7$Freq)
p5.7$C <- diff(p5.7$Marks)[1]
p5.7$A.idx <- 7
p5.7$A <- p5.7$Marks[p5.7$A.idx]
p5.7$u <- seq(1, length(p5.7$Marks), by=1)-p5.7$A.idx
p5.7$fu <- p5.7$Freq*p5.7$u
p5.7$fu2 <- p5.7$Freq*p5.7$u^2
p5.7$fu3 <- p5.7$Freq*p5.7$u^3
p5.7$fu4 <- p5.7$Freq*p5.7$u^4
Table.5.3 <- data.frame(X=p5.7$Marks, u=p5.7$u, f=p5.7$Freq, fu=p5.7$fu, fu2=p5.7$fu2, fu3=p5.7$fu3, fu4=p5.7$fu4)

#### Table 5-3

In [5]:
Table.5.3

   X   u  f  fu  fu2 fu3   fu4
1   70 -6  4 -24 144  -864  5184
2   74 -5  9 -45 225 -1125  5625
3   78 -4 16 -64 256 -1024  4096
4   82 -3 28 -84 252  -756  2268
5   86 -2 45 -90 180  -360   720
6   90 -1 66 -66  66   -66    66
7   94  0 85   0   0     0     0
8   98  1 72  72  72    72    72
9  102  2 54 108 216   432   864
10 106  3 38 114 342  1026  3078
11 110  4 27 108 432  1728  6912
12 114  5 18  90 450  2250 11250
13 118  6 11  66 396  2376 14256
14 122  7  5  35 245  1715 12005
15 126  8  2  16 128  1024  8192

In [6]:
cat('(a) m1.prime = ', (p5.7$m1.prime <- p5.7$C*sum(p5.7$fu)/p5.7$N), '\n')
cat('(b) m2.prime = ', (p5.7$m2.prime <- p5.7$C^2*sum(p5.7$fu2)/p5.7$N), '\n')
cat('(c) m3.prime = ', (p5.7$m3.prime <- p5.7$C^3*sum(p5.7$fu3)/p5.7$N), '\n')
cat('(d) m4.prime = ', (p5.7$m4.prime <- p5.7$C^4*sum(p5.7$fu4)/p5.7$N), '\n')
cat('(e) m1 = ', (p5.7$m1 <- 0), '\n')
cat('(f) m2 = m2.prime - m1.prime^2 = ', (p5.7$m2 <- p5.7$m2.prime - p5.7$m1.prime^2), '\n')
cat('(g) m3 = m3.prime - 3*m1.prime*m2.prime + 2*m1.prime^3 = ', (p5.7$m3 <- p5.7$m3.prime - 3*p5.7$m1.prime*p5.7$m2.prime + 2*p5.7$m1.prime^3), '\n')
cat('(h) m4 = m4.prime - 4*m1.prime*m3.prime + 6*m1.prime^2*m2.prime - 3*m1.prime^4 = ', (p5.7$m4 <- p5.7$m4.prime - 4*p5.7$m1.prime*p5.7$m3.prime + 6*p5.7$m1.prime^2*p5.7$m2.prime - 3*p5.7$m1.prime^4), '\n')
cat('(i) X.bar = (A+d).bar = A + m1.prime = A + c sum(fu)/N = ', (p5.7$X.bar <- p5.7$A + p5.7$C*sum(p5.7$fu)/p5.7$N), '\n')
cat('(j) s = sqrt(m2) = ', (p5.7$s <- sqrt(p5.7$m2)), '\n')
cat('(i) X.sq.bar = (A+d).sq.bar = (A^2 + 2Ad + d^2).bar = A^2 + 2A(d.bar) + d.sq.bar = A^2 + 2Am1.prime + m2.prime = ',
    (p5.7$X.sq.bar <- p5.7$A^2 + 2*p5.7$A*p5.7$m1.prime + p5.7$m2.prime), '\n')
cat('(k) X.qube.bar = (A+d).qube.bar = (A^3 + 3A^2d+3Ad^2 + d^3).bar = A^3 + 3A^2m1.prime + 3Am2.prime + m3.prime = ',
    (p5.7$X.qube.bar <- p5.7$A^3 + 3*p5.7$A^2*p5.7$m1.prime + 3*p5.7$A*p5.7$m2.prime + p5.7$m3.prime), '\n')

(a) m1.prime =  1.966667
(b) m2.prime =  113.4667
(c) m3.prime =  857.0667
(d) m4.prime =  39780.27
(e) m1 =  0
(f) m2 = m2.prime - m1.prime^2 =  109.5989
(g) m3 = m3.prime - 3*m1.prime*m2.prime + 2*m1.prime^3 =  202.8266
(h) m4 = m4.prime - 4*m1.prime*m3.prime + 6*m1.prime^2*m2.prime - 3*m1.prime^4 =  35626.31
(i) X.bar = (A+d).bar = A + m1.prime = A + c sum(fu)/N =  95.96667
(j) s = sqrt(m2) =  10.46895
(i) X.sq.bar = (A+d).sq.bar = (A^2 + 2Ad + d^2).bar = A^2 + 2A(d.bar) + d.sq.bar = A^2 + 2Am1.prime + m2.prime =  9319.2
(k) X.qube.bar = (A+d).qube.bar = (A^3 + 3A^2d+3Ad^2 + d^3).bar = A^3 + 3A^2m1.prime + 3Am2.prime + m3.prime =  915571.1