# The semi-interquartile range

## Problem 4.6
Find the semi-interquartile range for the height distribution of the students at XYZ University (see Table [4.1](#Table-4-1) of Problem [4.4](#Problem-4-4).

In [3]:
load('../../Saves//Table_4.1.Rdata')
Table.4.1

  Height X  X.X.bar Freq f.X.X.bar
1 60-62  61 6.45     5   32.25
2 63-65  64 3.45    18   62.10
3 66-68  67 0.45    42   18.90
4 69-71  70 2.55    27   68.85
5 72-74  73 5.55     8   44.40

### Solution 4-6
The lower and upper quartiles are $Q_1 = 65.5 + \frac{2}{42}(3) = 65.64$ in and $Q_3 = 68.5 + \frac{10}{27}(3) = 69.61$ in, respectively, and the semi-interquartile range (or quartile deviation) is $Q = \frac{1}{2}(Q_3 - Q_1) = \frac{1}{2}(69.61 - 65.64) = 1.98$ in. Note that $50\%$ of the cases lie between $Q_1$ and $Q_3$. (i.e., $50$ students have heights between $65.64$ and $69.61$ in).  
We can consider $\frac{1}{2}(Q_1 + Q_3) = 67.63$ in to be a measure of central tendency (i.e., average height). It follows that $50\%$ of the height lie in the range $67.63\pm1.98$ in.

In [56]:
p4.6 <- new.env()
p4.6$C <- 3
p4.6$Class.Boundaries <- tail(seq(59.5, 74.5, by=3),-1)
p4.6$Freq <- Table.4.1$Freq
p4.6$Cumsum <- cumsum(p4.6$Freq)
p4.6$Q.Breaks <- sum(p4.6$Freq)/4

p4.6$Q1.Class.End <- head(p4.6$Freq[p4.6$Cumsum > p4.6$Q.Breaks],1)
p4.6$Q1.Class.Remainder <- p4.6$Q.Breaks - tail(p4.6$Cumsum[p4.6$Cumsum < p4.6$Q.Breaks],1)
p4.6$Q1.Last.Class.Boundary <- tail(p4.6$Class.Boundaries[p4.6$Cumsum < p4.6$Q.Breaks],1)
p4.6$Q1 <- round(p4.6$Q1.Last.Class.Boundary + p4.6$Q1.Class.Remainder/p4.6$Q1.Class.End*p4.6$C,2)
cat('Q1 =', p4.6$Q1, '\n')

p4.6$Q3.Class.End <- head(p4.6$Freq[p4.6$Cumsum > 3*p4.6$Q.Breaks],1)
p4.6$Q3.Class.Remainder <- 3*p4.6$Q.Breaks - tail(p4.6$Cumsum[p4.6$Cumsum < 3*p4.6$Q.Breaks],1)
p4.6$Q3.Last.Class.Boundary <- tail(p4.6$Class.Boundaries[p4.6$Cumsum < 3*p4.6$Q.Breaks],1)
p4.6$Q3 <- round(p4.6$Q3.Last.Class.Boundary + p4.6$Q3.Class.Remainder/p4.6$Q3.Class.End*p4.6$C,2)
cat('Q3 =', p4.6$Q3, '\n')

p4.6$Q <- (p4.6$Q3 - p4.6$Q1)/2
cat('Q =', p4.6$Q, 'in\n')

cat('50% of all heights are between:', ((p4.6$Q1 + p4.6$Q3)/2)-c(p4.6$Q, -p4.6$Q), 'in\n')

Q1 = 65.64
Q3 = 69.61
Q = 1.985 in
50% of all heights are between: 65.64 69.61 in

In [57]:
rm(p4.6)

---

## Problem 4-7
Find the semi-interquartile range for the wages of the 65 employees at the P&R Comapny (see Table [2.6](#Table-2-6) of Problem [2.3](#Problem-2-6)).

In [59]:
load('../../Saves//Table_2.6.Rdata')
Table.2.6

  Wages           Number.of.employees
1 $250.00-$259.99  8
2 260.00-269.99   10
3 270.00-279.99   16
4 280.00-289.99   14
5 290.00-299.99   10
6 300.00-309.99    5
7 310.00-319.99    2

### Solution 4-7
From Problem [3.44](#Problem-3-44). $Q_1=\$268.25$ and $Q_3=\$290.75$. Thus the semi-interquartile range $Q=\frac{1}{2}(Q_3-Q_1)=\frac{1}{2}(\$290.75-\$268.25)=\$11.25$. Since $\frac{1}{2}(Q_1+Q_3)=\$279.50$, we can conclude that $50\%$ of the employees earn wages lying in the range $\$279.50\pm\$11.25$.

In [101]:
p4.7 <- new.env()
p4.7$C <- round((259.99-250.00))
p4.7$Class.Boundaries <- tail(seq(249.995, 319.995, by=p4.7$C),-1)
p4.7$Freq <- Table.2.6$Number.of.employees
p4.7$Cumsum <- cumsum(p4.7$Freq)
p4.7$Q.Breaks <- sum(p4.7$Freq)/4

p4.7$Q1.Class.End <- head(p4.7$Freq[p4.7$Cumsum > p4.7$Q.Breaks],1)
p4.7$Q1.Class.Remainder <- p4.7$Q.Breaks - tail(p4.7$Cumsum[p4.7$Cumsum < p4.7$Q.Breaks],1)
p4.7$Q1.Last.Class.Boundary <- tail(p4.7$Class.Boundaries[p4.7$Cumsum < p4.7$Q.Breaks],1)
p4.7$Q1 <- round(p4.7$Q1.Last.Class.Boundary + p4.7$Q1.Class.Remainder/p4.7$Q1.Class.End*p4.7$C,2)

p4.7$Q3.Class.End <- head(p4.7$Freq[p4.7$Cumsum > 3*p4.7$Q.Breaks],1)
p4.7$Q3.Class.Remainder <- 3*p4.7$Q.Breaks - tail(p4.7$Cumsum[p4.7$Cumsum < 3*p4.7$Q.Breaks],1)
p4.7$Q3.Last.Class.Boundary <- tail(p4.7$Class.Boundaries[p4.7$Cumsum < 3*p4.7$Q.Breaks],1)
p4.7$Q3 <- round(p4.7$Q3.Last.Class.Boundary + p4.7$Q3.Class.Remainder/p4.7$Q3.Class.End*p4.7$C,2)

p4.7$Q <- (p4.7$Q3 - p4.7$Q1)/2
p4.7$Central.Tendency <- (p4.7$Q1 + p4.7$Q3)/2
p4.7$Q.Range <- p4.7$Central.Tendency - c(p4.7$Q, -p4.7$Q)
cat('The semi-interquartile range is: $', p4.7$Q.Range[1], ' - $', p4.7$Q.Range[2],
    '. Or $', p4.7$Central.Tendency, ' +/- $', p4.7$Q, '\n', sep='')

The semi-interquartile range is: $268.24 - $290.74. Or $279.49 +/- $11.25

In [102]:
rm(p4.7)

---