# The arithmetic mean

## Problem-3-53
A student received grades of $85$, $76$, $93$, $82$, and $96$ in five subjects. Determine the arithmetic mean of the grades.

### Solution-3-53
\begin{align}
\bar{X}=\frac{\sum{X}}{N}=\frac{85+76+93+82+96}{5} = 86.4
\end{align}

In [1]:
p3.53 <- new.env()
p3.53$data <- c(85,76,93,82,96)
round(mean(p3.53$data))
rm(p3.53)

[1] 86

---

## Problem-3-54
The reaction times of an individual to certain stimuli were measured by a psychologist to be $0.53$, $0.46$, $0.50$, $0.49$, $0.52$, $0.53$, $0.44$, and $0.55$ seconds respectively. Determine the mean reaction time of the individual to the stimuli.

### Solution-3-54
\begin{align}
\bar{X}=\frac{\sum{X}}{N}=\frac{0.53+0.46+0.50+0.49+0.52+0.53+0.44+0.55}{8} = 0.50 \text{ seconds}
\end{align}

In [2]:
p3.54 <- new.env()
p3.54$data <- c(0.53,0.46,0.50,0.49,0.52,0.53,0.44,0.55)
round(mean(p3.54$data),2)
rm(p3.54)

[1] 0.5

---

## Problem-3-55
A set of numbers consists of six $6$'s, seven $7$'s, eight $8$'s, nine $9$'s and ten $10$'s. What is the arithmetic mean of the numbers?

### Solution-3-55
\begin{align}
\bar{X}=\frac{\sum^K_{j=1}{f_jX_j}}{\sum^K_{j=1}{f_j}}=\frac{(6\cdot6)+(7\cdot7)+(8\cdot8)+(9\cdot9)+(10\cdot10)}{6+7+8+9+10} = 8.25
\end{align}

In [3]:
p3.55 <- new.env()
p3.55$X <- c(6,7,8,9,10)
p3.55$frequency <- c(6,7,8,9,10)
round(weighted.mean(p3.55$X,p3.55$frequency),2)
rm(p3.55)

[1] 8.25

---

## Problem-3-56
A student's grades in the laboratory, lecture, and recitation parts of a physics course were $71$, $78$, and $89$, respectively.  
(a) If the weights accorded these grades are $2$, $4$, and $5$, respectively, what is an appropriate average grade?  
(b) What is the average grade if equal weights are used?

### Solution-3-56

In [4]:
p3.56 <- new.env()
p3.56$X <- c(71,78,89)
p3.56$weights <- c(2,4,5)
cat("(a)", round(weighted.mean(p3.56$X,p3.56$weights)), "\n")
cat("(b)", round(mean(p3.56$X)))
rm(p3.56)

(a) 82
(b) 79

---

## Problem-3-57
Three teachers of economics reported mean examination grades of $79$, $74$, and $82$ in their classes, which consisted of $32$, $25$, and $17$ students, respectively. Determine the mean grade for all the classes.

### Solution-3-57

In [5]:
p3.57 <- new.env()
p3.57$X <- c(79,74,82)
p3.57$weights <- c(32,25,17)
round(weighted.mean(p3.57$X,p3.57$weights))
rm(p3.57)

[1] 78

---

## Problem-3-58
The mean annual salary paid to all employees in a company is $\$36\,000$. The mean annual salaries paid to male and female employees of the company is $\$34\,000$ and $\$40\,000$ respectively. Determine the percentage of males and females employed by the company.

### Solution-3-58

In [6]:
p3.58 <- new.env()
p3.58$mean <- 36000
p3.58$mean.male <- 34000
p3.58$mean.female <- 40000
p3.58$A <- matrix(c(p3.58$mean.male, 1, p3.58$mean.female, 1),2,2)
p3.58$b <- matrix(c(p3.58$mean,1),2,1)
p3.58$pct.male.female <- round(solve(p3.58$A,p3.58$b)*100,2)

cat("Percent Male: ",p3.58$pct.male.female[1],"\n")
cat("Percent Female: ",p3.58$pct.male.female[2], "\n")
rm(p3.58)

Percent Male:  66.67
Percent Female:  33.33

---

## Problem-3-59
Table [3.8](#Table-3-8) shows the distribution of the maximum loads in short tons ($1$ short ton = $2\,000$lb) supported by certain cables produced by a company. Determine the mean maximum loading, using (a) the long method and (b) the coding method.

In [1]:
load("../../Saves/Table_3.8.Rdata")

#### Table-3-8

In [2]:
Table.3.8

  Max.Load.low Max.Load.high Number.of.Cables
1  9.3          9.7           2
2  9.8         10.2           5
3 10.3         10.7          12
4 10.8         11.2          17
5 11.3         11.7          14
6 11.8         12.2           6
7 12.3         12.7           3
8 12.8         13.2           1

### Solution-3-59
The long method is defined in equation [(2)](../01%20Text/04%20The%20arithmetic%20mean.ipynb#eq2):
\begin{align}
\bar{X}=\frac{f_1X_1+f_2X_2+\ldots+f_KX_K}{f_1+f_2+\ldots+f_K}=\frac{\sum^K_{j=1}{f_jX_j}}{\sum^K_{j=1}{f_j}}=\frac{\sum{fX}}{\sum{f}}=\frac{\sum{fX}}{N}
\end{align}

The coding method is defined in equation [(7)](../01%20Text/07%20The%20arithmetic%20mean%20computed%20from%20grouped%20data.ipynb#eq7):
\begin{align}\label{eq7}\tag{7}
\bar{X}=A+\left(\frac{\sum^K_{j=1}{f_ju_j}}{N}\right)=A + \left(\frac{\sum{fu}}{N}\right)c
\end{align}

In [9]:
p3.59a <- new.env()
p3.59a$X <- c(9.3+(9.7-9.3)/2,9.8+(10.2-9.8)/2,10.3+(10.7-10.3)/2,10.8+(11.2-10.8)/2,
             11.3+(11.7-11.3)/2,11.8+(12.2-11.8)/2,12.3+(12.7-12.3)/2,12.8+(13.2-12.8)/2)
p3.59a$f <- Table.3.8$Number.of.Cables
p3.59a$X.bar <- round(sum(p3.59a$f*p3.59a$X)/sum(p3.59a$f),2)
cat("Using the long method: ", p3.59a$X.bar)
rm(p3.59a)

Using the long method:  11.09

In [10]:
p3.59b <- new.env()
p3.59b$X <- c(9.3+(9.7-9.3)/2,9.8+(10.2-9.8)/2,10.3+(10.7-10.3)/2,10.8+(11.2-10.8)/2,
             11.3+(11.7-11.3)/2,11.8+(12.2-11.8)/2,12.3+(12.7-12.3)/2,12.8+(13.2-12.8)/2)
p3.59b$length <- length(p3.59b$X)
p3.59b$A.idx <- ceiling(p3.59b$length/2)
p3.59b$A <- p3.59b$X[p3.59b$A.idx]
p3.59b$u <- seq(1,p3.59b$length,by=1)-p3.59b$A.idx
p3.59b$f <- Table.3.8$Number.of.Cables
p3.59b$fu <- p3.59b$f*p3.59b$u
p3.59b$N <- sum(p3.59b$f)
p3.59b$c <- 9.7-9.3
p3.59b$X.bar <- round(p3.59b$A+(sum(p3.59b$fu)/p3.59b$N)*p3.59b$c,2)
cat("Using the coding method: ",p3.59b$X.bar)
rm(p3.59b)
rm(Table.3.8)

Using the coding method:  11.07

---

## Problem-3-60
Find $\bar{X}$ for the data in Table [(3.9)](#Table-3-9), using (a) the long method and (b) the coding method.

In [11]:
load("../../Saves/Table_3.9.Rdata")

#### Table-3-9

In [12]:
Table.3.9

  [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
X 462  480  498  516  534  552  570  588  606  624
f  98   75   56   42   30   21   15   11    6    2

### Solution-3-60
The long method is defined in equation [(2)](../01%20Text/04%20The%20arithmetic%20mean.ipynb#eq2):
\begin{align}
\bar{X}=\frac{f_1X_1+f_2X_2+\ldots+f_KX_K}{f_1+f_2+\ldots+f_K}=\frac{\sum^K_{j=1}{f_jX_j}}{\sum^K_{j=1}{f_j}}=\frac{\sum{fX}}{\sum{f}}=\frac{\sum{fX}}{N}
\end{align}

The coding method is defined in equation [(7)](../01%20Text/07%20The%20arithmetic%20mean%20computed%20from%20grouped%20data.ipynb#eq7):
\begin{align}\label{eq7}\tag{7}
\bar{X}=A+\left(\frac{\sum^K_{j=1}{f_ju_j}}{N}\right)=A + \left(\frac{\sum{fu}}{N}\right)c
\end{align}

In [13]:
p3.60a <- new.env()
p3.60a$X <- Table.3.9["X",]
p3.60a$f <- Table.3.9["f",]
p3.60a$X.bar <- round(sum(p3.60a$X*p3.60a$f)/sum(p3.60a$f),1)
cat("The long method: ", p3.60a$X.bar,"\n")
rm(p3.60a)

The long method:  501

In [14]:
p3.60b <- new.env()
p3.60b$X <- Table.3.9["X",]
p3.60b$f <- Table.3.9["f",]
p3.60b$length <- length(p3.60b$X)
p3.60b$c <- diff(p3.60b$X)[1]
p3.60b$A.idx <- ceiling(p3.60b$length/2)
p3.60b$A <- p3.60b$X[p3.60b$A.idx]
p3.60b$u <- seq(1,p3.60b$length,by=1)-p3.60b$A.idx
p3.60b$fu <- p3.60b$f*p3.60b$u
p3.60b$X.bar <- round(p3.60b$A+sum(p3.60b$fu)/sum(p3.60b$f)*p3.60b$c,1)
cat("The coded method: ", p3.60b$X.bar,"\n")
rm(p3.60b)
rm(Table.3.9)

The coded method:  501

---

## Problem-3-61
Table [(3.10)](#Table-3-10) shows the distribution of the diameters (in centimeters) of the heads of rivets manufactured by a company. Compute the mean diameter.

In [15]:
load("../../Saves/Table_3.10.Rdata")

#### Table-3-10

In [16]:
Table.3.10

   Diameter.low Diameter.high Frequency
1  0.7247       0.7249         2
2  0.7250       0.7252         6
3  0.7253       0.7255         8
4  0.7256       0.7258        15
5  0.7259       0.7261        42
6  0.7262       0.7264        68
7  0.7265       0.7267        49
8  0.7268       0.7270        25
9  0.7271       0.7273        18
10 0.7274       0.7276        12
11 0.7277       0.7279         4
12 0.7280       0.7282         1

### Solution-3-61

In [17]:
p3.61 <- new.env()
p3.61$X <- (Table.3.10$Diameter.high-Table.3.10$Diameter.low)/2+Table.3.10$Diameter.low
p3.61$f <- Table.3.10$Frequency
p3.61$X.bar <- round(weighted.mean(p3.61$X,p3.61$f),5)
cat("The mean diameter of the rivets:", p3.61$X.bar, "cm\n")
rm(p3.61)
rm(Table.3.10)

The mean diameter of the rivets: 0.72642 cm

---

## Problem-3-62
Compute the mean for the data in Table [(3.11)](#Table-3-11).

In [18]:
load("../../Saves/Table_3.11.Rdata")

#### Table-3-11

In [19]:
Table.3.11

  Class.low Class.under Frequency
1 10        15           3
2 15        20           7
3 20        25          16
4 25        30          12
5 30        35           9
6 35        40           5
7 40        45           2

### Solution-3-62

In [20]:
p3.62 <- new.env()
p3.62$X <- (Table.3.11$Class.under-Table.3.11$Class.low)/2+Table.3.11$Class.low
p3.62$f <- Table.3.11$Frequency
p3.62$X.bar <- round(weighted.mean(p3.62$X,p3.62$f),1)
cat("Mean:", p3.62$X.bar,"\n")
rm(p3.62)
rm(Table.3.11)

Mean: 26.2

---

## Problem-3-63
Compute the mean TV viewing time for $400$ junior high students per week in Problem [(2.20)](../../02%20Chapter%202%20Frequency%20Distributions/03%20Supplementary%20Problems/Supplementary%20problems.ipynb#Problem-2-20)

In [21]:
load("../../Saves/Table_2.15.Rdata")

In [22]:
p3.63 <- new.env()
p3.63$f <- Table.2.15$Number.of.Students
p3.63$X <- (Table.2.15$Viewing.Time.high-Table.2.15$Viewing.Time.low)/2 + Table.2.15$Viewing.Time.low
p3.63$X.bar <- weighted.mean(p3.63$X,p3.63$f)
cat("The mean TV viewing time for the 400 junior high students per week:", p3.63$X.bar, "minutes\n")
rm(p3.63)
rm(Table.2.15)

The mean TV viewing time for the 400 junior high students per week: 715 minutes

---

## Problem-3-64
(a) Use the frequency distribution obtained in Problem [(2.27)](../../02%20Chapter%202%20Frequency%20Distributions/03%20Supplementary%20Problems/Supplementary%20problems.ipynb#Problem-2-27) to compute the mean diameter of the ball bearings.  
(b) Compute the mean directly from the raw data and compare it with part (a), explaining any discrepancy.

In [23]:
load("../../Saves/Problem_2.27.Rdata")

### Solution-3-64

In [24]:
p3.64a <- new.env()
p3.64a$histogram <- hist(Problem.2.27,plot=FALSE)
p3.64a$X <- p3.64a$histogram$mids
p3.64a$f <- p3.64a$histogram$counts
p3.64a$X.bar <- weighted.mean(p3.64a$X,p3.64a$f)
cat("(a) Mean diameter computed from frequency distribution:", round(p3.64a$X.bar,3), "cm\n")
cat("(b) The mean computed from the raw data:",round(mean(Problem.2.27),3),"cm\n")
cat("The discrpency is due to the fact that data is lost when grouping data into frequency distributions.")
rm(p3.64a)
rm(Problem.2.27)

(a) Mean diameter computed from frequency distribution: 1.734 cm
(b) The mean computed from the raw data: 1.735 cm
The discrpency is due to the fact that data is lost when grouping data into frequency distributions.